services:
  test:
    build: .
    volumes:
      - ./test-src:/var/task
    ports:
      - '9005:8080'
  chromium:
    build: with-chromium
    volumes:
      - ./test-src:/var/task
    ports:
      - '9006:8080'